"""
        Celegans

A module to capture idiosincrasis of the particular organism
"""
module Celegans

using DataFrames
using Base.Filesystem

"""

        neuron_list

A dataframe describing what we know about individual C.elegans neurons. Generated by the preprocesing script and re-read from Celegans.Files.neuronList.

This is populated on module load time with info from 

"""
neuron_list = DataFrame()

"""
        indexByName

A dictionary of neuron indices by their name.

Initialized at module load tiem. 

See also: nameByIndex
"""
indexByName = Dict{String, Int64}()

function getIndexByName(NeuronName::String)
    return(get(indexByName,NeuronName,nothing))
end

"""

        nameByIndex

An inverse index-to-names for each neuron. Maintained as an array and thus accessible.
"""
nameByIndex = Vector{String}()

# FVA: TODO retake this function when we know more about defining state
# function __init__()
#     global neuron_list =
#         CSV.read(joinpath("data",Celegans.Files.neuronList),
#                  DataFrame;
#                  stringtype=String);

#     global nameByIndex = neuron_list.Neuron;
#     @assert all(map(x -> nameByIndex[indexByName[x]] == x,nameByIndex))
#     @assert all(map(x -> indexByName[nameByIndex[x]] == x,1:nNeurons))

#     global nameByIndex = neuron_list.Neuron;


# end


include("celegans_constants.jl");

include("celegans_functions.jl");

include("celegans_files.jl");#Submodule Files

export neuron_list, indexByName, getIndexByName, nameByIndex, 
    # celegans_constants.jl
    nNeurons,
    E_exc, E_inh,
    spikeThresh,
    Ecell,
    beta,
    specific_capacitance,
    C,
    intracellular_resistivity,
    gᵞ, 
    Gc, 
    ar,
    ad,

    #celegans_functions.jl
    connectomeToMultivaluedMatrix,
    connectomeToBinaryMatrix,

    #Paths to different datasets both raw and after preprocessing
    Files
end

